### PR TITLE
include content rating (other than “safe”) as a tag for MangaDex

### PR DESCRIPTION
**Pull request by henderea**
I have seen this requested before, and I had done this in the fork I maintain for personal use, so I figured I might as well offer the improvement to the main fork.

### CODE REVIEW

**Comment by TheNetsky** [comment]
I don't really see this point of this?

Tags are just local on each devices and won't update locally unless source is refreshed/reinstalled.

Besides if the user changes the content setting, they know what they're doing, no need to add a tag for them.

Tags are meant for people to see what kind of content the source offers on quick glance.

**Comment by henderea** [comment]
Well, I just thought I'd offer it up since I know some people want it. There isn't really any other way to see that info for an individual series. The MangaDex website shows them alongside the tags on the search results, so I don't think it's particularly weird. But you can reject it if you don't agree with the idea. I have my own fork, so I don't really mind one way or the other.

**Comment by TheNetsky** [comment]
Oh wait, my bad. I thinking about the wrong section. I thought this was meant for the sourceTags. Not the individual manga tags. However since this is a source a lot of people use, I will need to personally check it when I have time before I merge anything.

**Comment by TheNetsky** [comment]
After looking into it, this will just add a "tag" that when clicked will not yield any search results. I'm not comfortable adding a code to add this search functionality for something quite niche.

**Comment by henderea** [comment]
You can tap on a tag to search for it? That's news to me. I suppose if it would make that experience awkward, it's fine to not do this change. I use my own fork for MangaDex anyway, so I was just sharing this change for other people to use.

**Pull request closed without merging**
