### PR TITLE
randomize the user agent; fixes #49

### LINKED ISSUE #49: nHentai Cloudflare bypass not working
**Describe the bug**

When trying to do the cloudflare bypass it keeps getting stuck.

**To Reproduce**
1. Go to 'settings'
2. Click on 'nHentai '
3. Scroll down to 'Cloudflare bypass and click on it '

**Expected behavior**

Should be able to finish the Cloudflare bypass once the captcha is completed 

**Screenshots/Video**

https://user-images.githubusercontent.com/87585497/231527860-aacea46a-8ce5-4c48-8954-ea6b0891b06e.MOV

**App version**
- v0.7-r46

**Source WITH source version**
- nHentai 3.2.4

**Additional context**

### PR DESCRIPTION
**Pull request by henderea**

### CODE REVIEW

**Comment by TheNetsky** [comment]
Uhhh, I wouldn't actually use the "random-useragent" library. It produces many old user agents, recently Cloudflare started not allowing those through. I'd either use a different library or another method of generating user agents.

**Comment by henderea** [comment]
I actually grabbed that code from the madera repo

**Comment by TheNetsky** [comment]
I know but that was made back when Cloudflare didn't blacklist old user agents, and I'm not updating 0.6 sources anymore.

**Comment by henderea** [comment]
How about <https://www.npmjs.com/package/user-agents>? That was updated less than 24 hours ago and seems pretty popular.

**Comment by TheNetsky** [comment]
Try and see

**Comment by henderea** [comment]
Well, that didn’t work any better than the one i started with.  Either way, it can take multiple tries, but the old library from the madera stuff still works fine if you try a few times.

**Comment by niclimcy** [comment]
User agents can’t all be that unique, even on the latest ios version the useragent is:

Mozilla/5.0 (iPhone; CPU iPhone OS 16_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Mobile/15E148 Safari/604.1

and yet cloudflare does not actively block this.

Maybe having a ci to update to the latest user agent instead every new iOS release might work better than staying on ancient user agent?

**Comment by xOnlyFadi** [comment]
Maybe this one will work 
https://www.npmjs.com/package/rand-user-agent

**Comment by henderea** [comment]
> Maybe this one will work
> https://www.npmjs.com/package/rand-user-agent

Well, it *looks* like a decent option, but i can’t get it to build.

```
> extensions-official@1.0.0 bundle
> paperback bundle

[10:39:36:0974] Working directory: /home/coder/projects/extensions-sources-netsky
[10:39:36:0975] 
src/tests/NHentai.test.ts(6,1): error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
src/tests/NHentai.test.ts(10,57): error TS6133: 'should' is declared but its value is never read.
src/tests/NHentai.test.ts(21,5): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
src/tests/NHentai.test.ts(25,21): error TS2339: Property 'id' does not exist on type 'Manga'.
src/tests/NHentai.test.ts(31,5): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
src/tests/NHentai.test.ts(36,5): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
src/tests/NHentai.test.ts(39,72): error TS2532: Object is possibly 'undefined'.
src/tests/NHentai.test.ts(50,5): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
src/tests/NHentai.test.ts(51,28): error TS2304: Cannot find name 'createSearchRequest'.
src/tests/NHentai.test.ts(60,16): error TS2532: Object is possibly 'undefined'.
src/tests/NHentai.test.ts(61,16): error TS2532: Object is possibly 'undefined'.
src/tests/NHentai.test.ts(62,16): error TS2532: Object is possibly 'undefined'.
src/tests/NHentai.test.ts(63,16): error TS2532: Object is possibly 'undefined'.
src/tests/NHentai.test.ts(64,16): error TS2532: Object is possibly 'undefined'.
src/tests/NHentai.test.ts(65,16): error TS2532: Object is possibly 'undefined'.
src/tests/NHentai.test.ts(69,5): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
src/tests/NHentai.test.ts(70,28): error TS2304: Cannot find name 'createSearchRequest'.
src/tests/NHentai.test.ts(78,16): error TS2532: Object is possibly 'undefined'.
src/tests/NHentai.test.ts(79,16): error TS2532: Object is possibly 'undefined'.
src/tests/NHentai.test.ts(80,16): error TS2532: Object is possibly 'undefined'.
src/tests/NHentai.test.ts(83,5): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
src/tests/NHentai.test.ts(84,28): error TS2304: Cannot find name 'createSearchRequest'.
src/tests/NHentai.test.ts(92,16): error TS2532: Object is possibly 'undefined'.
src/tests/NHentai.test.ts(93,16): error TS2532: Object is possibly 'undefined'.
src/tests/NHentai.test.ts(94,16): error TS2532: Object is possibly 'undefined'.
src/tests/NHentai.test.ts(97,5): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
src/tests/NHentai.test.ts(98,28): error TS2304: Cannot find name 'createSearchRequest'.
src/tests/NHentai.test.ts(103,19): error TS6133: 'search' is declared but its value is never read.
src/tests/NHentai.test.ts(111,5): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
src/tests/NHentai.test.ts(112,28): error TS2304: Cannot find name 'createSearchRequest'.
src/tests/NHentai.test.ts(122,5): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
src/tests/NHentai.test.ts(129,16): error TS2532: Object is possibly 'undefined'.
src/tests/NHentai.test.ts(130,16): error TS2532: Object is possibly 'undefined'.
src/tests/NHentai.test.ts(131,16): error TS2532: Object is possibly 'undefined'.
src/tests/NHentai.test.ts(134,5): error TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
[10:39:39:0061] # Transpiling project: 2076ms
[10:39:39:0061] 
[10:39:39:0071] Tests directory, skipping
[10:39:39:0071] - Building tests: 0ms
node:events:490
      throw er; // Unhandled 'error' event
      ^

Error: Can't walk dependency graph: Cannot find module 'rand-user-agent' from '/home/coder/projects/extensions-sources-netsky/temp_build/NHentai/NHentaiSettings.js'
    required by /home/coder/projects/extensions-sources-netsky/temp_build/NHentai/NHentaiSettings.js
    at /home/coder/projects/extensions-sources-netsky/node_modules/resolve/lib/async.js:137:35
    at processDirs (/home/coder/projects/extensions-sources-netsky/node_modules/resolve/lib/async.js:290:39)
    at isdir (/home/coder/projects/extensions-sources-netsky/node_modules/resolve/lib/async.js:297:32)
    at /home/coder/projects/extensions-sources-netsky/node_modules/resolve/lib/async.js:25:69
    at FSReqCallback.oncomplete (node:fs:195:21)
Emitted 'error' event on Readable instance at:
    at Labeled.<anonymous> (/home/coder/projects/extensions-sources-netsky/node_modules/read-only-stream/index.js:28:44)
    at Labeled.emit (node:events:512:28)
    at Labeled.<anonymous> (/home/coder/projects/extensions-sources-netsky/node_modules/stream-splicer/index.js:130:18)
    at Labeled.emit (node:events:512:28)
    at Deps.<anonymous> (/home/coder/projects/extensions-sources-netsky/node_modules/stream-splicer/index.js:130:18)
    at Deps.emit (node:events:512:28)
    at /home/coder/projects/extensions-sources-netsky/node_modules/module-deps/index.js:387:25
    at onresolve (/home/coder/projects/extensions-sources-netsky/node_modules/module-deps/index.js:185:25)
    at /home/coder/projects/extensions-sources-netsky/node_modules/browserify/index.js:528:22
    at /home/coder/projects/extensions-sources-netsky/node_modules/browser-resolve/index.js:265:24 {
  code: 'MODULE_NOT_FOUND',
  stream: Labeled {
    _readableState: ReadableState {
      objectMode: true,
      highWaterMark: 16,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: Labeled {
        _readableState: ReadableState {
          objectMode: true,
          highWaterMark: 16,
          buffer: BufferList { head: null, tail: null, length: 0 },
          length: 0,
          pipes: Labeled {
            _readableState: [ReadableState],
            readable: true,
            _events: [Object: null prototype],
            _eventsCount: 8,
            _maxListeners: undefined,
            _writableState: [WritableState],
            writable: true,
            allowHalfOpen: true,
            _options: [Object],
            _wrapOptions: [Object],
            _streams: [Array],
            length: 1,
            label: 'unbom',
            [Symbol(kCapture)]: false
          },
          pipesCount: 1,
          flowing: true,
          ended: false,
          endEmitted: false,
          reading: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          destroyed: false,
          defaultEncoding: 'utf8',
          awaitDrain: 0,
          readingMore: false,
          decoder: null,
          encoding: null
        },
        readable: true,
        _events: [Object: null prototype] {
          end: [ [Function], [Function], [Function] ],
          finish: [ [Function], [Function] ],
          error: [ [Function: onerror], [Function (anonymous)] ],
          unpipe: [Function: onunpipe],
          drain: [Function (anonymous)],
          close: [Function: bound onceWrapper] {
            listener: [Function: onclose]
          },
          data: [Function: ondata],
          _mutate: [Function: bound onceWrapper] {
            listener: [Function: onreadable]
          }
        },
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: WritableState {
          objectMode: true,
          highWaterMark: 16,
          finalCalled: false,
          needDrain: false,
          ending: false,
          ended: false,
          finished: false,
          destroyed: false,
          decodeStrings: true,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: false,
          bufferProcessing: false,
          onwrite: [Function (anonymous)],
          writecb: null,
          writelen: 0,
          bufferedRequest: null,
          lastBufferedRequest: null,
          pendingcb: 0,
          prefinished: false,
          errorEmitted: false,
          bufferedRequestCount: 0,
          corkedRequestsFree: CorkedRequest {
            next: null,
            entry: null,
            finish: [Function (anonymous)]
          }
        },
        writable: true,
        allowHalfOpen: true,
        _options: { objectMode: true },
        _wrapOptions: { objectMode: true },
        _streams: [
          DestroyableTransform {
            _readableState: [ReadableState],
            readable: true,
            _events: [Object: null prototype],
            _eventsCount: 4,
            _maxListeners: undefined,
            _writableState: [WritableState],
            writable: true,
            allowHalfOpen: true,
            _transformState: [Object],
            _destroyed: false,
            _transform: [Function (anonymous)],
            [Symbol(kCapture)]: false
          }
        ],
        length: 1,
        label: 'json',
        [Symbol(kCapture)]: false
      },
      pipesCount: 1,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] {
      end: [
        [Function: bound onceWrapper] { listener: [Function: onend] },
        [Function: bound onceWrapper] {
          listener: [Function (anonymous)]
        },
        [Function: bound onceWrapper] { listener: [Function: onend] }
      ],
      error: [Function (anonymous)],
      data: [Function: ondata],
      _mutate: [Function: bound onceWrapper] { listener: [Function: onreadable] }
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: true,
      highWaterMark: 16,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function (anonymous)],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: CorkedRequest {
        next: null,
        entry: null,
        finish: [Function (anonymous)]
      }
    },
    writable: false,
    allowHalfOpen: true,
    _options: { objectMode: true },
    _wrapOptions: { objectMode: true },
    _streams: [
      Deps {
        _readableState: ReadableState {
          objectMode: true,
          highWaterMark: 16,
          buffer: BufferList { head: null, tail: null, length: 0 },
          length: 0,
          pipes: null,
          pipesCount: 0,
          flowing: null,
          ended: false,
          endEmitted: false,
          reading: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: true,
          resumeScheduled: false,
          destroyed: false,
          defaultEncoding: 'utf8',
          awaitDrain: 0,
          readingMore: false,
          decoder: null,
          encoding: null
        },
        readable: true,
        _events: [Object: null prototype] {
          end: [ [Function], [Function] ],
          prefinish: [Function: prefinish],
          file: [Function (anonymous)],
          package: [Function (anonymous)],
          transform: [Function (anonymous)],
          error: [Function (anonymous)],
          readable: [Function: bound onceWrapper] {
            listener: [Function: onreadable]
          }
        },
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: WritableState {
          objectMode: true,
          highWaterMark: 16,
          finalCalled: false,
          needDrain: false,
          ending: true,
          ended: true,
          finished: true,
          destroyed: false,
          decodeStrings: true,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: true,
          bufferProcessing: false,
          onwrite: [Function (anonymous)],
          writecb: null,
          writelen: 0,
          bufferedRequest: null,
          lastBufferedRequest: null,
          pendingcb: 0,
          prefinished: true,
          errorEmitted: false,
          bufferedRequestCount: 0,
          corkedRequestsFree: CorkedRequest {
            next: null,
            entry: null,
            finish: [Function (anonymous)]
          }
        },
        writable: false,
        allowHalfOpen: true,
        _transformState: {
          afterTransform: [Function: bound afterTransform],
          needTransform: true,
          transforming: false,
          writecb: null,
          writechunk: null,
          writeencoding: 'utf8'
        },
        basedir: '/home/coder/projects/extensions-sources-netsky',
        persistentCache: [Function (anonymous)],
        cache: undefined,
        fileCache: undefined,
        pkgCache: {
          '/home/coder/projects/extensions-sources-netsky/temp_build/NHentai/package.json': false,
          '/home/coder/projects/extensions-sources-netsky/temp_build/package.json': false,
          '/home/coder/projects/extensions-sources-netsky/package.json': {
            name: 'extensions-official',
            repositoryName: 'Extensions NSFW (Netsky Fork)',
            version: '1.0.0',
            description: 'Community maintained Paperback extension repository',
            main: 'index.js',
            scripts: [Object],
            repository: [Object],
            author: 'Paperback Community',
            license: 'GPL-3.0-or-later',
            bugs: [Object],
            homepage: 'https://github.com/Paperback-iOS/extensions-official#readme',
            devDependencies: [Object],
            dependencies: [Object],
            __dirname: '/home/coder/projects/extensions-sources-netsky'
          },
          '/home/coder/projects/extensions-sources-netsky/temp_build/NHentai/NHentai.js': {
            name: 'extensions-official',
            repositoryName: 'Extensions NSFW (Netsky Fork)',
            version: '1.0.0',
            description: 'Community maintained Paperback extension repository',
            main: 'index.js',
            scripts: [Object],
            repository: [Object],
            author: 'Paperback Community',
            license: 'GPL-3.0-or-later',
            bugs: [Object],
            homepage: 'https://github.com/Paperback-iOS/extensions-official#readme',
            devDependencies: [Object],
            dependencies: [Object],
            __dirname: '/home/coder/projects/extensions-sources-netsky'
          },
          '/home/coder/projects/extensions-sources-netsky/node_modules/browserify/lib/package.json': false,
          '/home/coder/projects/extensions-sources-netsky/node_modules/browserify/package.json': {
            name: 'browserify',
            version: '17.0.0',
            description: 'browser-side require() the node way',
            main: 'index.js',
            bin: [Object],
            repository: [Object],
            engines: [Object],
            keywords: [Array],
            dependencies: [Object],
            devDependencies: [Object],
            author: [Object],
            scripts: [Object],
            license: 'MIT',
            __dirname: '/home/coder/projects/extensions-sources-netsky/node_modules/browserify'
          },
          '/home/coder/projects/extensions-sources-netsky/node_modules/browserify/lib/_empty.js': {
            name: 'browserify',
            version: '17.0.0',
            description: 'browser-side require() the node way',
            main: 'index.js',
            bin: [Object],
            repository: [Object],
            engines: [Object],
            keywords: [Array],
            dependencies: [Object],
            devDependencies: [Object],
            author: [Object],
            scripts: [Object],
            license: 'MIT',
            __dirname: '/home/coder/projects/extensions-sources-netsky/node_modules/browserify'
          }
        },
        pkgFileCache: {},
        pkgFileCachePending: {},
        _emittedPkg: {
          '/home/coder/projects/extensions-sources-netsky': true,
          '/home/coder/projects/extensions-sources-netsky/node_modules/paperback-extensions-common': true,
          '/home/coder/projects/extensions-sources-netsky/node_modules/browserify': true
        },
        _transformDeps: {},
        visited: {
          '/home/coder/projects/extensions-sources-netsky/temp_build/NHentai/NHentai.js': true,
          '/home/coder/projects/extensions-sources-netsky/temp_build/NHentai/NHentaiHelper.js': true,
          '/home/coder/projects/extensions-sources-netsky/temp_build/NHentai/NHentaiSettings.js': true,
          '/home/coder/projects/extensions-sources-netsky/temp_build/NHentai/NHentaiParser.js': true,
          '/home/coder/projects/extensions-sources-netsky/node_modules/paperback-extensions-common/dist/index.js': true,
          '/home/coder/projects/extensions-sources-netsky/node_modules/browserify/lib/_empty.js': true
        },
        walking: {},
        entries: [
          '/home/coder/projects/extensions-sources-netsky/temp_build/NHentai/NHentai.js'
        ],
        _input: [ { row: [Object], pkg: [Object] } ],
        paths: [],
        transforms: [],
        globalTransforms: [ [ [Function: globalTr], [Object] ] ],
        resolver: [Function (anonymous)],
        detective: [Function (anonymous)] { find: [Function (anonymous)] },
        options: {
          standalone: 'Sources',
          entries: [
            '/home/coder/projects/extensions-sources-netsky/temp_build/NHentai/NHentai.js'
          ],
          dedupe: true,
          expose: {},
          extensions: [ '.js', '.json' ],
          transform: [],
          transformKey: [ 'browserify', 'transform' ],
          postFilter: [Function (anonymous)],
          filter: [Function (anonymous)],
          resolve: [Function (anonymous)],
          modules: {
            assert: '/home/coder/projects/extensions-sources-netsky/node_modules/assert/assert.js',
            buffer: '/home/coder/projects/extensions-sources-netsky/node_modules/buffer/index.js',
            child_process: '/home/coder/projects/extensions-sources-netsky/node_modules/browserify/lib/_empty.js',
            cluster: '/home/coder/projects/extensions-sources-netsky/node_modules/browserify/lib/_empty.js',
            console: '/home/coder/projects/extensions-sources-netsky/node_modules/console-browserify/index.js',
            constants: '/home/coder/projects/extensions-sources-netsky/node_modules/constants-browserify/constants.json',
            crypto: '/home/coder/projects/extensions-sources-netsky/node_modules/crypto-browserify/index.js',
            dgram: '/home/coder/projects/extensions-sources-netsky/node_modules/browserify/lib/_empty.js',
            dns: '/home/coder/projects/extensions-sources-netsky/node_modules/browserify/lib/_empty.js',
            domain: '/home/coder/projects/extensions-sources-netsky/node_modules/domain-browser/source/index.js',
            events: '/home/coder/projects/extensions-sources-netsky/node_modules/events/events.js',
            fs: '/home/coder/projects/extensions-sources-netsky/node_modules/browserify/lib/_empty.js',
            http: '/home/coder/projects/extensions-sources-netsky/node_modules/stream-http/index.js',
            https: '/home/coder/projects/extensions-sources-netsky/node_modules/https-browserify/index.js',
            http2: '/home/coder/projects/extensions-sources-netsky/node_modules/browserify/lib/_empty.js',
            inspector: '/home/coder/projects/extensions-sources-netsky/node_modules/browserify/lib/_empty.js',
            module: '/home/coder/projects/extensions-sources-netsky/node_modules/browserify/lib/_empty.js',
            net: '/home/coder/projects/extensions-sources-netsky/node_modules/browserify/lib/_empty.js',
            os: '/home/coder/projects/extensions-sources-netsky/node_modules/os-browserify/browser.js',
            path: '/home/coder/projects/extensions-sources-netsky/node_modules/path-browserify/index.js',
            perf_hooks: '/home/coder/projects/extensions-sources-netsky/node_modules/browserify/lib/_empty.js',
            punycode: '/home/coder/projects/extensions-sources-netsky/node_modules/browserify/node_modules/punycode/punycode.js',
            querystring: '/home/coder/projects/extensions-sources-netsky/node_modules/querystring-es3/index.js',
            readline: '/home/coder/projects/extensions-sources-netsky/node_modules/browserify/lib/_empty.js',
            repl: '/home/coder/projects/extensions-sources-netsky/node_modules/browserify/lib/_empty.js',
            stream: '/home/coder/projects/extensions-sources-netsky/node_modules/stream-browserify/index.js',
            _stream_duplex: '/home/coder/projects/extensions-sources-netsky/node_modules/readable-stream/duplex.js',
            _stream_passthrough: '/home/coder/projects/extensions-sources-netsky/node_modules/readable-stream/passthrough.js',
            _stream_readable: '/home/coder/projects/extensions-sources-netsky/node_modules/readable-stream/readable.js',
            _stream_transform: '/home/coder/projects/extensions-sources-netsky/node_modules/readable-stream/transform.js',
            _stream_writable: '/home/coder/projects/extensions-sources-netsky/node_modules/readable-stream/writable.js',
            string_decoder: '/home/coder/projects/extensions-sources-netsky/node_modules/string_decoder/lib/string_decoder.js',
            sys: '/home/coder/projects/extensions-sources-netsky/node_modules/util/util.js',
            timers: '/home/coder/projects/extensions-sources-netsky/node_modules/timers-browserify/main.js',
            tls: '/home/coder/projects/extensions-sources-netsky/node_modules/browserify/lib/_empty.js',
            tty: '/home/coder/projects/extensions-sources-netsky/node_modules/tty-browserify/index.js',
            url: '/home/coder/projects/extensions-sources-netsky/node_modules/url/url.js',
            util: '/home/coder/projects/extensions-sources-netsky/node_modules/util/util.js',
            vm: '/home/coder/projects/extensions-sources-netsky/node_modules/vm-browserify/index.js',
            zlib: '/home/coder/projects/extensions-sources-netsky/node_modules/browserify-zlib/lib/index.js',
            _process: '/home/coder/projects/extensions-sources-netsky/node_modules/process/browser.js'
          },
          globalTransform: []
        },
        pending: 10,
        inputPending: 0,
        top: {
          id: '/home/coder/projects/extensions-sources-netsky/__fake.js',
          filename: '/home/coder/projects/extensions-sources-netsky/__fake.js',
          paths: [],
          basedir: '/home/coder/projects/extensions-sources-netsky'
        },
        _ended: true,
        [Symbol(kCapture)]: false
      }
    ],
    length: 1,
    label: 'deps',
    [Symbol(kCapture)]: false
  }
}

Node.js v19.8.1
```

**Comment by niclimcy** [comment]
> > Maybe this one will work
> > https://www.npmjs.com/package/rand-user-agent
> 
> Well, it _looks_ like a decent option, but i can’t get it to build.

Its so new that it doesn’t have typescript types package for it. You have to import it and access it like a javascript module

**Comment by henderea** [comment]
I swear it had a type definition built in. I'm not sure a missing type definition would do this anyway.

VS Code opened up a typescript definition when I command-clicked the import. So I'm pretty sure this isn't a missing type def.

**Comment by xOnlyFadi** [comment]
> Well, it _looks_ like a decent option, but i can’t get it to build.

im gonna try it on my end and see the package works

**Comment by xOnlyFadi** [comment]
found out a way to make it work with commonjs package i can give the new version on discord for it to work

**Comment by henderea** [comment]
Alright, I’ve put in the changes, and they seem to work.  I switched the code from @xOnlyFadi around to import the json file from the actual package instead of including the data in a TypeScript file, which meant I had to turn on JSON module resolution in the `tsconfig.json`, but hopefully no one minds me turning that on to simplify the data update process.  Doing it this way means getting updated data only requires updating the version of the package, which is MUCH easier.  I think netsky would be a lot more willing to update a package than to fetch the data and convert it into a TS file.

It doesn’t seem to be 100% perfect at generating good values, since my first generated UA was considered outdated, but I think it probably has a higher success rate than `random-useragent`, since my second and third tries were both fine.

As a note, I’m actually testing this stuff on my personal self-hosted fork, which is based on this one but with a few minor tweaks. But the relevant code is all exactly the same, so the test should be valid.

**Pull request merged**
